# 7.2 데이터 변형
# 7.2.1 중복 제거하기

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                    'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [4]:
data.duplicated() # 중복된 로우 확인 가능

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [5]:
data.drop_duplicates() # 중복된 로우를 제거한다

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [6]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])  # k1과 중복인 것을 걸러내는 작업

k1  k2  v1
0  one   1   0
1  two   1   1

In [7]:
data.drop_duplicates(['k1', 'k2'], keep='last') # duplicate는 기본적으로 처음 발견된 값을 유지하는데, keep='last'를 쓰면 마지막으로 발견된 값을 유지한다

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

- 7.2.2 함수나 매핑을 이용해서 데이터 변형하기

In [8]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                   'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [9]:
meat_to_aniaml = {
    'bacon' : 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [10]:
lowercased = data['food'].str.lower()  # str.lower매서드를 이용하면 모두 소문자로 변경할 수 있다.

In [11]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [12]:
data['animal'] = lowercased.map(meat_to_aniaml)  # mapping을 이용해서 아래처럼 표를 합칠 수 있다
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [13]:
data['food'].map(lambda x: meat_to_aniaml[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

- 7.2.3 값 치환하기

In [14]:
data1 = pd.Series([1., -999., 2., -999., -1000., 3.])
data1

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [18]:
data1.replace(-999., np.nan)  # replace를 이용하면 값을 바꿀 수 있다.

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [19]:
data1.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [20]:
data1.replace([-999, -1000], [np.nan, 0]) # 각각 대응되는 값으로 치환된다

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [23]:
data1.replace({-999: np.nan, -1000:0}) # 위와 같다 list나 dict 타입으로 바꿔서 사용할 수 있다.

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

- 7.2.4 축 색인 이름 바꾸기

In [29]:
data2 = pd.DataFrame(np.arange(12).reshape((3,4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'threee', 'four'])
data2

one  two  threee  four
Ohio        0    1       2     3
Colorado    4    5       6     7
New York    8    9      10    11

In [30]:
transform = lambda x: x[:4].upper()  # 다음 함수로 바꿀 수 있다

In [31]:
data2.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [33]:
data2.index = data2.index.map(transform)  # 바로 축을 index에 바꿀 수 있다.
data2

one  two  threee  four
OHIO    0    1       2     3
COLO    4    5       6     7
NEW     8    9      10    11

In [34]:
data2.rename(index=str.title, columns=str.upper)  # 원본을 바꾸지 않고 쓰려면 rename을 쓰면 된다.

ONE  TWO  THREEE  FOUR
Ohio    0    1       2     3
Colo    4    5       6     7
New     8    9      10    11

In [35]:
data2

one  two  threee  four
OHIO    0    1       2     3
COLO    4    5       6     7
NEW     8    9      10    11

In [39]:
data2.rename(index={'OHIO': 'INDIANA'},
           columns={'threee':'peakaboo'})

one  two  peakaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [40]:
data2.rename(index={'OHIO': 'INDIANA'}, inplace=True) # inplace 를 이용하면 rename을 쓰더라도 원본을 바꿀 수 있다.

In [41]:
data2

one  two  threee  four
INDIANA    0    1       2     3
COLO       4    5       6     7
NEW        8    9      10    11

- 7.2.5 개별화와 양자화

In [42]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [45]:
bins = [18, 25, 35, 60, 100]

In [46]:
cats = pd.cut(ages, bins)  # cut함수를 이용하여 bin에 들어가있는 숫자 간격의 그룹으로 나눌 수 있다
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [47]:
cats.codes  # ages의 원소가 cut으로 인해서 나누어진 그룹의 어디에 속하는지를 보여준다

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [48]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [49]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [50]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [53]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']  # 그룹의 이름을 직접 설정할 수 있음

In [54]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [55]:
data3 = np.random.rand(20)

In [56]:
data3

array([0.85606522, 0.12471504, 0.70725151, 0.26395101, 0.2852019 ,
       0.6627482 , 0.27924126, 0.40252123, 0.89361292, 0.90792733,
       0.11116593, 0.97794879, 0.18075771, 0.14873414, 0.4822475 ,
       0.48596653, 0.96958545, 0.17626298, 0.28277043, 0.50698827])

In [57]:
pd.cut(data3, 4, precision=2)  # precision=2 소수점 2째자리 까지, 옆에 처럼 명시적으로 그룹의 구분을 주지 않아도 4 처럼 숫자를 적어주면 자동으로 계산해서 계산해준다.

[(0.76, 0.98], (0.11, 0.33], (0.54, 0.76], (0.11, 0.33], (0.11, 0.33], ..., (0.33, 0.54], (0.76, 0.98], (0.11, 0.33], (0.11, 0.33], (0.33, 0.54]]
Length: 20
Categories (4, interval[float64]): [(0.11, 0.33] < (0.33, 0.54] < (0.54, 0.76] < (0.76, 0.98]]

In [59]:
data4 = np.random.randn(1000) # 정규분포
catss = pd.qcut(data4, 4)  # qcut을 이용하면 표본 변위치를 사용하여 그룹을 나눈다
catss

[(-0.672, 0.00488], (0.00488, 0.664], (0.664, 3.054], (0.00488, 0.664], (-3.151, -0.672], ..., (-3.151, -0.672], (-0.672, 0.00488], (0.664, 3.054], (0.664, 3.054], (0.664, 3.054]]
Length: 1000
Categories (4, interval[float64]): [(-3.151, -0.672] < (-0.672, 0.00488] < (0.00488, 0.664] < (0.664, 3.054]]

In [60]:
catss.value_counts()

(-3.151, -0.672]     250
(-0.672, 0.00488]    250
(0.00488, 0.664]     250
(0.664, 3.054]       250
dtype: int64

In [63]:
pd.qcut(data4, [0, 0.1, 0.5, 0.9, 1.]) # 옆과 같이 변위치를 직접 지정할 수도 있다

[(-1.264, 0.00488], (0.00488, 1.25], (0.00488, 1.25], (0.00488, 1.25], (-1.264, 0.00488], ..., (-1.264, 0.00488], (-1.264, 0.00488], (0.00488, 1.25], (1.25, 3.054], (0.00488, 1.25]]
Length: 1000
Categories (4, interval[float64]): [(-3.151, -1.264] < (-1.264, 0.00488] < (0.00488, 1.25] < (1.25, 3.054]]

In [64]:
pd.qcut(data4, [0, 0.1, 0.5, 0.9, 1.]).value_counts() 

(-3.151, -1.264]     100
(-1.264, 0.00488]    400
(0.00488, 1.25]      400
(1.25, 3.054]        100
dtype: int64

- 7.2.6 특잇값을 찾고 제외하기

In [65]:
data5 = pd.DataFrame(np.random.randn(1000, 4))
data5.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.019837    -0.002617     0.013308     0.002767
std       0.987966     0.981306     1.003440     0.992367
min      -2.828148    -2.944649    -3.046705    -3.039038
25%      -0.676658    -0.698914    -0.663461    -0.682388
50%       0.013503     0.005265     0.011885     0.003898
75%       0.663639     0.648839     0.710446     0.699311
max       3.224310     2.691826     3.148763     3.311750

In [69]:
col = data5[2]

In [67]:
col[np.abs(col)>3]  # col에서 절댓값이 3이 초과하는 값

25     3.148763
613   -3.046705
Name: 2, dtype: float64

In [70]:
data5[(np.abs(data5) > 3).any(1)]  # 절댓값 3을 넘는 모든 로우를 확인할 수 있음

0         1         2         3
25   1.298844 -0.098604  3.148763  2.795222
613  2.315144 -0.217081 -3.046705 -0.130785
748 -0.314972  0.201576 -0.242411  3.311750
812  3.224310 -1.336462 -0.529640 -1.478455
833 -0.375163 -0.110199  0.275313 -3.039038

In [71]:
data5[np.abs(data5) > 3] = np.sign(data5) * 3 # 이 코드를 이용해 원하는 절댓값을 초과하는 값을 최대 절댓값으로 바꿀 수 있다.
data5.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.019612    -0.002617     0.013206     0.002494
std       0.987263     0.981306     1.002844     0.991255
min      -2.828148    -2.944649    -3.000000    -3.000000
25%      -0.676658    -0.698914    -0.663461    -0.682388
50%       0.013503     0.005265     0.011885     0.003898
75%       0.663639     0.648839     0.710446     0.699311
max       3.000000     2.691826     3.000000     3.000000

In [72]:
np.sign(data5).head()  # np.sign == 양수 음수에 따라 1이나 -1을 반환

0    1    2    3
0 -1.0 -1.0  1.0  1.0
1  1.0  1.0 -1.0 -1.0
2 -1.0 -1.0 -1.0 -1.0
3  1.0 -1.0  1.0 -1.0
4  1.0  1.0 -1.0 -1.0

- 7.2.7 치환과 임의 샘플링

In [74]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5,4)))

In [75]:
sampler = np.random.permutation(5)  # 랜덤으로 순서를 바꾸어서 정수배열이 만들어진다.
sampler

array([3, 0, 1, 4, 2])

In [76]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [77]:
df.take(sampler)  # 위의 배열은 iloc 기반의 색인이나 take에서 사용가능

0   1   2   3
3  12  13  14  15
0   0   1   2   3
1   4   5   6   7
4  16  17  18  19
2   8   9  10  11

In [78]:
df.sample(n=3)  # dataFrame의 일부의 값만 가져오는 방법은 sample 매서드를 이용하면 가능하다.

0   1   2   3
1   4   5   6   7
3  12  13  14  15
2   8   9  10  11

In [79]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True)  # 반복 선택을 허용하는 경우에서 표본을 치환을 통해 생성가능
draws

0    5
0    5
2   -1
3    6
2   -1
0    5
0    5
1    7
3    6
0    5
dtype: int64

- 7.2.8 표시자/더미 변수 계산하기

In [80]:
df = pd.DataFrame({'key': ['b', 'b', 'a','c', 'a', 'b'],
                  'data1': range(6)})
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [81]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)  # 기존 데이터와 더미를 만들어서 합치는 방법. 'prefix로 사용가능'
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [82]:
mnames = ['moie_id', 'title', 'genres']
movies = pd.read_table('pydata-book/datasets/movielens/movies.dat', sep='::',
                      header=None, names=mnames)
movies[:10]

/Users/ihoon/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py:765: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return read_csv(**locals())


moie_id                               title                        genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy
5        6                         Heat (1995)         Action|Crime|Thriller
6        7                      Sabrina (1995)                Comedy|Romance
7        8                 Tom and Huck (1995)          Adventure|Children's
8        9                 Sudden Death (1995)                        Action
9       10                    GoldenEye (1995)     Action|Adventure|Thriller

In [83]:
all_genres = []

In [84]:
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)

In [85]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [86]:
zero_matrix = np.zeros((len(movies), len(genres)))
dummies1 = pd.DataFrame(zero_matrix, columns=genres)

In [87]:
gen = movies.genres[0]

In [88]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [89]:
dummies1.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [90]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies1.iloc[i, indices] = 1

In [91]:
movies_windic = movies.join(dummies1.add_prefix('Genre_'))
movies_windic.iloc[0]

moie_id                                        1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                0
Genre_Children's                               0
Genre_Comedy                                   0
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [92]:
np.random.seed(12345)  # 시드값을 설정하니 책과 값이 똑같이 나왔넹

In [93]:
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [94]:
bins1 = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [95]:
pd.get_dummies(pd.cut(values, bins1))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0